### ISSUE TITLE
Proposal for new module

### ISSUE THREAD

**Issue by Yorgosgr** [XthemeOrg/xtheme-contrib-modules#3]
Hello all,

I had an idea for a new module that could be implemented. I am not good in coding so i am throwing my idea:

The module can be called ns_mute. it will operate the same way as ns_freeze (/ns mute nick on reason) but when the user identifies to the nickname he gets shunned.

Can this be made or is it a total waste of your time?

**Comment by GLolol** [comment]
I'm not sure if shun is available in all IRCds, so such a module would be limited to certain IRCds.

**Comment by jdhore** [comment]
I personally don't think SHUN is a good idea. You should just ban users in this case. Users will almost always figure out that they've been shunned.

Also, the proper way to implement this would be similar to the way SQLINE/SGLINE are implemented. ie: adding a SHUN handler in all the protocol modules that support SHUN and calling that with the proper parameters.

**Comment by siniStar7boy** [comment]
Such a module is definitely possible, _but it would in essence be a waste of time._ (As pointed out above -- it is easy for users to figure out that they are shunned; and the affected users would simply stop identifying to NickServ.) 
_This would make the module useless (and a waste of time)._  I appreciate your interest in enhancing Xtheme, _however_.
