### ISSUE TITLE
ns_forbid: Add to NickServ LIST output

### ISSUE THREAD

**Issue by siniStar7boy** [XthemeOrg/xtheme-contrib-modules#5]
**ns_forbid:** It was proposed by Maro on IRC (as well as XthemeOrg/Xtheme#51) that forbidden nicknames should also be visible in the **NickServ LIST** output.   Since this is a contrib module, XthemeOrg/Xtheme#51 is also being referenced in XthemeOrg/xtheme-contrib-modules.

**Suggested by MrMaro via XthemeOrg/Xtheme#51:**
I suggest xtheme should have forbidden list such as frozen list in the /msg NickServ HELP LIST. Currently we cant track which nick has been forbid and list of them

Suggested command : /ns list forbidden

**Comment by siniStar7boy** [comment]
_After speaking with Maro more about this request on IRC, it was determined that the true functionality that he was wanting in ns_forbid is not applicable to his situation.  ns_forbid works on un-registered users, **not registered users**.  Forbidding a registered nickname from using their nickname can already be done via ircd, etc._

Functionality could be changed so that forbidden nicks are actually shown in LIST as forbidden, (currently they are shown as frozen) but i am not sure that is really necessary.  

**More opinions/comments are welcome on this issue.**

**Comment by MrMaro** [comment]
If you think forbid is only suitable for non registered nick, i have no problem on that. But it must be listed somewhere like /ns list forbidden

**Comment by siniStar7boy** [comment]
_It's not necessarily that I think forbid is suitable only for non-registered nicknames,_ but that is how it currently functions.  

As I said before, changing the functionality so that forbidden nicks are shown in LIST as forbidden is a possibility, **but is it really necessary, beneficial, or is ns_forbid even used by (m)any networks?**  _(That's why this is remaining open for discussion)_
